//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLiSinhVien.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Teacher
    {
        public int ID { get; set; }
        public string TeacherName { get; set; }
        public int ClassID { get; set; }
        public string Roles { get; set; }
        public string Username { get; set; }
    
        public virtual Class Class { get; set; }
        public virtual LoginInfor LoginInfor { get; set; }
    }
}
